src/account/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from . import views

app_name = 'account'

urlpatterns = [
    path('', views.AccountView.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('my_page/<int:pk>/', views.MyPage.as_view(), name='my_page'),
    path('signup/', views.Signup.as_view(), name='signup'),
    path('signup_done/', views.SignupDone.as_view(), name='signup_done'),
    path('user_update/<int:pk>', views.UserUpdate.as_view(), name='user_update'),
    path('reset_password/', views.PasswordReset.as_view(), name='reset_password'),
    path('password_reset_sent', views.PasswordResetSent.as_view(), name='password_reset_sent'),
    path('password_reset_confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change_done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('delete/<int:pk>', views.UserDeleteView.as_view(), name='delete'),
    path('delete_done/', views.UserDeleteDoneView.as_view(), name='delete_done'),
    path('favorite_items/', views.FavoriteItems, name='favorite_items')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/ec_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('top/', include('top.urls')),
    path('account/', include('account.urls')),
    path('items/', include('items.urls')),
    path('settlement/', include('settlement.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/items/urls.py
from django.urls import include, path

from . import views

app_name = 'items'

urlpatterns = [
    path('add_item_page/', views.Add_Item_page, name='add_item'),
    path('add_item_completed/', views.Add_Item_Completed, name='add_item_completed'),
    path('item_details/<int:item_id>/', views.Item_Detail, name='item_details'),
    path('item_details/<int:item_id>/like/', views.LikeItem.as_view(), name='like'),
]

src/top/urls.py
from django.urls import include, path

from . import views

app_name = 'top'

urlpatterns = [
    path('', views.TopView, name='top')
]

src/top/views.py
from django.shortcuts import render
from django.views import generic
from django.db.models import Q

from items.models import Item


# Create your views here.
class TopView(generic.TemplateView):
    template_name = 'top.html'

# Topページを表示するためのビュー
def TopView(request):
    if request.method == "POST":
        SearchWord = request.POST.get("search")
        print(SearchWord)
        items_list = Item.objects.filter(
            Q(item_title__contains=SearchWord) |
            Q(item_explain__contains=SearchWord)
        )
    else:
        items_list = Item.objects.all()
    context = {
        "items_list":items_list,
    }
    return render(request, "top.html", context)

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ECサイト</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'top:top' %}"><img src="{% static 'img/top/logo.png' %}"
                    class="col-5"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
                <form class="form-inline my-2 my-lg-0" method="POST">
                    {% csrf_token %}
                    <input class="form-control mr-sm-2" type="search" placeholder="検索" aria-label="Search" name="search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">検索</button>
                </form>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">

                        {% if not user.is_authenticated %}
                        <a href="{% url 'account:login' %}" class="btn btn-dark" role="button">ログイン</a>
                        {% else %}
                        <div class="dropdown">
                            <button id="btnOpenMenu" class="btn btn-dark dropdown-toggle" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                                ユーザメニュー
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="btnOpenMenu">
                                <li><a class="dropdown-item" href="{% url 'account:favorite_items' %}">お気に入り</a></li>
                                <li><a class="dropdown-item" href="{% url 'account:my_page' user.pk %}">マイページ</a></li>
                                <li><a class="dropdown-item" href="{% url 'account:logout' %}">ログアウト</a></li>
                            </ul>
                        </div>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <!-- ここにコンテンツを追加 -->
        {% block content %}
        {% endblock %}
    </div>

    <div id="footer">
        <p>&copy; 2024 Your Website | Designed by K.kojima</p>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    {% block js %}
    {% endblock %}  
</body>

</html>

src/templates/return_to_Top.html
{% extends 'base,html' %}

{% block content %}
<div class="container">
    <h3>問題が発生しました</h3>
    <a href="{% url 'top:top' %}">Topページへ戻る</a>
</div>
{% endblock %}

src/templates/top.html
{% extends 'base.html' %} {% block content %}

<a href="{%url 'items:add_item' %}">出品する</a>
<div class="row row-cols-md-3">
  {% for item in items_list %}
  <div class="col" style="margin: 0 0 40px 0; width: 380px; height: 534px">
    <div class="card" style="width: 90%; height: 100%">
      {% if item.item_image%}
      <img
        src="{{ item.item_image.url }}"
        class="card-img-top"
        style="object-fit: contain; height: 80%"
        alt=""
      />
      {% else %}
      <img
        src="\media\item_images\item_None\20220110-00051273-bunshun-000-2-view.jpg"
        class="card-img-top"
        style="object-fit: contain"
        alt=""
      />
      {% endif %}
      <div class="card-body" style="height: 20%">
        {% if item.is_bought == False %}
        <h5 class="card-title">
          <a
            href="{% url 'items:item_details' item.id %}"
            target="_blank"
            rel="noopener noreferrer"
            >{{item.item_title}}</a
          >
        </h5>
        {% else %}
        <h5 class="card-title text-muted">売り切れ</h5>
        {% endif %}
        <p class="card-text">{{item.seller}}</p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}