src/ec_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('top/', include('top.urls')),
    path('account/', include('account.urls')),
    path('items/', include('items.urls')),
    path('settlement/', include('settlement.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/settlement/urls.py
from django.urls import include, path

from . import views

app_name = 'settlement'

urlpatterns = [
    path('AddressSelect/<int:item_id>', views.confirm, name='AddressSelect'),
    path('AddAddress/<int:user_id>', views.AddAddress.as_view(), name='AddAddress'),
    path('payment/', views.PayView.as_view(), name='payment')
]

src/top/urls.py
from django.urls import include, path

from . import views

app_name = 'top'

urlpatterns = [
    path('', views.TopView, name='top')
]

src/settlement/models.py
from django.db import models

from account.models import User
from items.models import Item


# Create your models here.
class Trade(models.Model):
    purchaser = models.ForeignKey(User, on_delete=models.CASCADE, related_name='payment_user')
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='payment_item')
    price = models.IntegerField()

src/settlement/views.py
import payjp
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.views import generic

from account.models import PaymentInfo, User, User_Additional_Address
from items.models import Item

from .models import Trade


# Create your views here.
@login_required
def confirm(request, item_id):
    item = get_object_or_404(Item, pk=item_id)
    user = get_object_or_404(User, pk=request.user.pk)
    request.session['item'] = item_id
    if request.method == 'POST':
        Address = request.POST.get("Address")
        request.session["address"] = Address
        return redirect('settlement:payment')
    else:
        addresses = [user.address]
        AdditionalAddresses = User_Additional_Address.objects.filter(user=request.user.pk)
        for address in AdditionalAddresses:
            addresses.append(address)
        
        return render(request, 'settlement/AddressSelect.html', {'item':item, 'addresses':addresses})

class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        # 今ログインしてるユーザーのpkと、そのマイページのpkが同じなら許可
        user = self.request.user
        return user.pk == self.kwargs['user_id']

class AddAddress(OnlyYouMixin, generic.TemplateView):
    template_name = 'settlement/AddAddress.html'

    def post(self, request, user_id):
        AdditionalAddress =  request.POST.get("address")
        user = get_object_or_404(User, pk=user_id)
        NewAddress = User_Additional_Address(user=user, additional_address=AdditionalAddress)
        NewAddress.save()
        item_id = request.session['item']
        print(request.POST.get("item_price"))
        return redirect('settlement:AddressSelect', item_id=item_id)

class PayView(generic.View):
    """
    use PAY.JP API
    """
    
    def get(self, request):
        item = get_object_or_404(Item, pk=request.session['item'])
        amount = item.item_price
        # 公開鍵を渡す
        context = {"public_key": "pk_test_eec2c84ed893ec3da8110866",
                   "amount": amount,
                   }
        return render(
            request, "settlement/confirm.html", context
        )

    def post(self, request):
        item = get_object_or_404(Item, pk=request.session['item'])
        amount = item.item_price
        payjp_token = request.POST.get("payjp-token")

        # トークンから顧客情報を生成
        customer = payjp.Customer.create(email=request.user.email, card=payjp_token)
        # 支払いを行う
        charge = payjp.Charge.create(
            amount=amount,
            currency="jpy",
            customer=customer.id,
            description="Django example charge",
        )
        Trade.objects.create(item=item, purchaser=request.user, price=amount)
        
        #TODO 購入した商品を消去する
        bought_item = Item.objects.get(pk=request.session['item'])
        bought_item.is_bought = True
        bought_item.save()
        
        context = {"amount": amount, "customer": customer, "charge": charge}
        return render(request, "settlement/completed.html", context)

src/templates/settlement/AddAddress.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="col-md-6 offset-md-3">
        <div class="card mt-3 mb-3 bg-light">
            <!-- カードヘッダー -->
            <div class="card-header bg-success text-light">
                <h4>住所の追加</h4>
            </div>
            <!-- カードボディー -->
            <div class="card-body">
                <form action="" method="POST">
                    {% csrf_token %}
                    <label for="address">住所:</label>
                    <input type="text" name="address" id="address">
                    <!-- ボタン -->
                    <button type="submit" class="btn btn-success btn-lg btn-block mt-2" onclick="javascript:history.go(-1);">追加</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/templates/settlement/AddressSelect.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" id="SelectAddress">
    <div class="d-flex flex-row md-3 justify-content-around">
        <div>
            <h3>1．住所の登録</h3>
            <div class="d-flex flex-column justify-content-around">

                {% csrf_token %}
                {% for address in addresses %}
                <div class="form-check">
                    {% if forloop.counter0 == 0 %}
                    <input class="form-check-input" type="radio" value="{{address}}" name="Address"
                        id="Address{{forloop.counter0}}" checked>
                    {% else %}
                    <input class="form-check-input" type="radio" value="{{address}}" name="Address"
                        id="Address{{forloop.counter0}}">
                    {% endif %}
                    <label for="Address{{forloop.counter0}}">
                        {{address}}
                    </label>
                </div>
                {% endfor %}

                <a href="{% url 'settlement:AddAddress' request.user.pk %}">＋住所を追加する</a>
            </div>
        </div>
        <div>
            <h3>{{item.item_title}}</h3>
            <h5>{{item.item_price}}円</h5>
            <input type="hidden" name="item_price" value="{{item.item_price}}">
            <!-- <button class="btn btn-danger" type="submit" form="SelectAddress" onclick="static/js/add_item_price.js">決済画面に進む</button> -->
            <button class="btn btn-danger" type="submit" form="SelectAddress">決済画面に進む</button>
        </div>
    </div>
</form>
{% endblock %}

src/templates/settlement/completed.html
{% extends 'base.html' %}

{% block content %}
<h3>お支払いが完了しました．</h3>
<a href="{% url 'top:top' %}" class="btn btn-dark" role="button">買い物に戻る</a>
{% endblock %}

src/templates/settlement/confirm.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <article>
        <label>{{amount}}円のお支払い</label>
    </article>
    <script type="text/javascript" src="https://checkout.pay.jp/" class="payjp-button"
        data-key={{public_key}} data-submit-text="トークンを作成する" data-partial="true">
    </script>
    <button>購入する</button>
</form>

{% endblock %}

src/templates/settlement/stripe.html
{% extends 'base.html' %}

{% block content %}
<h3>item={{item}}</h3>
<h3>address={{address}}</h3>
<a href="{% url 'settlement:confirm' item %}" role="button" class="btn btn-dark">前のページに戻る</a>
{% endblock %}