src/account/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from . import views

app_name = 'account'

urlpatterns = [
    path('', views.AccountView.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('my_page/<int:pk>/', views.MyPage.as_view(), name='my_page'),
    path('signup/', views.Signup.as_view(), name='signup'),
    path('signup_done/', views.SignupDone.as_view(), name='signup_done'),
    path('user_update/<int:pk>', views.UserUpdate.as_view(), name='user_update'),
    path('reset_password/', views.PasswordReset.as_view(), name='reset_password'),
    path('password_reset_sent', views.PasswordResetSent.as_view(), name='password_reset_sent'),
    path('password_reset_confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change_done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('delete/<int:pk>', views.UserDeleteView.as_view(), name='delete'),
    path('delete_done/', views.UserDeleteDoneView.as_view(), name='delete_done'),
    path('favorite_items/', views.FavoriteItems, name='favorite_items')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/ec_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('top/', include('top.urls')),
    path('account/', include('account.urls')),
    path('items/', include('items.urls')),
    path('settlement/', include('settlement.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/top/urls.py
from django.urls import include, path

from . import views

app_name = 'top'

urlpatterns = [
    path('', views.TopView, name='top')
]

src/account/models.py
import os
import shutil
from uuid import uuid4

from django.contrib.auth.models import AbstractUser
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver


class CustomFileSystemStorage(FileSystemStorage):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def get_available_name(self, name, max_length=None):
        # ファイル名の重複を回避するために、ファイル名に一意のIDを付加します
        while self.exists(name):
            name = self.get_alternative_name(name)
        return name

    def _save(self, name, content):
        # ファイルを保存する前にフォルダを作成します
        dirname = os.path.dirname(name)
        if not os.path.exists(dirname):
            os.makedirs(dirname)
        return super()._save(name, content)




def user_directory_path(instance, filename):
    # ファイルアップロード時にユーザーIDをフォルダ名として使用する
    return f'profile_images/user_{instance.id}/{filename}'

class User(AbstractUser):
    # 追加のフィールドを定義します
    address = models.CharField(max_length=255, blank=True, null=True)
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    profile_image = models.ImageField(upload_to=user_directory_path, blank=True, null=True, storage=CustomFileSystemStorage())
    bio = models.TextField(blank=True, null=True)

class PaymentInfo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='payment_info')
    payment_details = models.CharField(max_length=255)
    # その他の支払い情報のフィールドを追加

    def __str__(self):
        return self.payment_details

class User_Additional_Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='additional_address')
    additional_address = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.additional_address

@receiver(post_delete, sender=User)
def delete_profile_image_folder(sender, instance, **kwargs):
    # ユーザーが削除されたときにプロフィール画像フォルダを削除する関数
    if instance.profile_image:
        folder_path = instance.profile_image.path.rsplit('/', 1)[0]
        shutil.rmtree(folder_path)
        folder_path = f'media/item_images/{instance.id}'
        shutil.rmtree(folder_path, ignore_errors=True)

src/account/forms.py
from typing import Any, Mapping
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.base_user import AbstractBaseUser  # ユーザーモデルを取得するため
from django.contrib.auth.forms import (AuthenticationForm, PasswordChangeForm,
                                       UserCreationForm, SetPasswordForm)
from django.forms.renderers import BaseRenderer
from django.forms.utils import ErrorList
from django.contrib.auth.hashers import make_password

# ユーザーモデル取得
User = get_user_model()


'''ログイン用フォーム'''
class LoginForm(AuthenticationForm):
    username = forms.CharField(label='ユーザー名かメールアドレス', max_length=254)
    # bootstrap4対応
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label  # placeholderにフィールドのラベルを入れる

class SignupForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('last_name', 'first_name', 'email','username', 'address', 'phone_number', 'profile_image', 'bio')
        labels = {
            'address':'住所',
            'phone_number':'電話番号',
            'profile_image':'プロフィール画像',
            'bio':'自己紹介文'
        }

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)
        self.fields['username'].required = False
        self.fields['profile_image'].required = False
        self.fields['bio'].required = False
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


            # オートフォーカスとプレースホルダーの設定
            print(field.label)
            if field.label == '姓':
                field.widget.attrs['autofocus'] = '' # 入力可能状態にする
                field.widget.attrs['placeholder'] = '田中'
            elif field.label == '名':
                field.widget.attrs['placeholder'] = '一郎'
            elif field.label == 'メールアドレス':
                field.widget.attrs['placeholder'] = '***@gmail.com'

class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('last_name', 'first_name', 'email', 'username','address', 'phone_number', 'profile_image', 'bio')
        labels = {
            'address':'住所',
            'phone_number':'電話番号',
            'profile_image':'プロフィール画像',
            'bio':'自己紹介文'
        }
    # bootstrap4対応
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].required = False
        self.fields['profile_image'].required = False
        self.fields['bio'].required = False
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class MyPasswordChangeForm(PasswordChangeForm):

    # bootstrap4対応で、classを指定
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class MySetPassword(SetPasswordForm):

    def __init__(self, user, *args, **kwargs) -> None:
        super().__init__(user, *args, **kwargs)
        self.fields["new_password1"].label = "新しいパスワード"
        self.fields["new_password2"].label = "新しいパスワード（確認）"
        self.fields["new_password1"].widget.attrs["placeholder"] = "８文字以上の英数字"
        self.fields["new_password2"].widget.attrs["placeholder"] = "確認用"

src/account/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.shortcuts import (HttpResponseRedirect, redirect, render,
                              resolve_url)
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views import generic

from items.models import Item

from .forms import (LoginForm, MyPasswordChangeForm, SetPasswordForm,
                    SignupForm, UserUpdateForm)
from .models import User


class AccountView(generic.TemplateView):
    template_name = 'accounts/top.html'

class Login(LoginView):
    form_class = LoginForm
    template_name = 'accounts/login.html'

class Logout(LogoutView):
    template_name = 'accounts/logout.html'

'''自分しかアクセスできないようにするMixin(My Pageのため)'''
class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        # 今ログインしてるユーザーのpkと、そのマイページのpkが同じなら許可
        user = self.request.user
        return user.pk == self.kwargs['pk']
    
'''マイページ'''
class MyPage(OnlyYouMixin, generic.DetailView):
    User = get_user_model()
    model = User
    template_name = 'accounts/my_page.html'
    # モデル名小文字(user)でモデルインスタンスがテンプレートファイルに渡される

'''サインアップ'''
class Signup(generic.CreateView):
    template_name = 'accounts/user_form.html'
    form_class =SignupForm

    def form_valid(self, form):
        user = form.save() # formの情報を保存
        return redirect('account:signup_done')

    # データ送信
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["process_name"] = "Sign up"
        return context


'''サインアップ完了'''
class SignupDone(generic.TemplateView):
    template_name = 'accounts/signup_done.html'

class UserUpdate(OnlyYouMixin, generic.UpdateView):
    User = get_user_model()
    model = User
    form_class = UserUpdateForm
    template_name = 'accounts/user_form.html'

    def get_success_url(self):
        return resolve_url('account:my_page', pk=self.kwargs['pk'])

    # contextデータ作成
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["process_name"] = "Update"
        return context
    
class PasswordChange(PasswordChangeView):
    form_class = MyPasswordChangeForm
    success_url = reverse_lazy('account:password_change_done')
    template_name = 'accounts/user_form.html'

    # contextデータ作成
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["process_name"] = "Change Password"
        return context

class PasswordChangeDone(PasswordChangeDoneView):
    template_name = 'accounts/password_change_done.html'

class UserDeleteView(OnlyYouMixin, generic.DeleteView):
    User = get_user_model()
    model = User
    template_name = 'accounts/delete.html'
    def get_success_url(self):
        return resolve_url('account:delete_done')
    
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        # 論理削除を行います。具体的な実装はモデルに依存します。
        self.object.is_active = 0
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

class UserDeleteDoneView(generic.TemplateView):
    template_name = 'accounts/delete_done.html'

class PasswordReset(PasswordResetView):
    subject_template_name = 'accounts/password_reset/subject.txt'
    email_template_name = 'accounts/password_reset/email.txt'
    template_name = 'accounts/password_reset/reset.html'
    success_url = reverse_lazy('account:password_reset_sent')

class PasswordResetSent(PasswordResetDoneView):
    template_name = 'accounts/password_reset/sent.html'

class PasswordResetConfirm(PasswordResetConfirmView):
    success_url = reverse_lazy('account:password_reset_complete')
    template_name = 'accounts/password_reset/confirm.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["process_name"] = "Password Reset"
        return context

class PasswordResetComplete(PasswordResetCompleteView):
    template_name = 'accounts/password_reset/complete.html'

def FavoriteItems(request):
    # ログインユーザーのお気に入りアイテムを取得    
    user = request.user
    # favorite_items = user.item_set.all()
    favorite_items = Item.objects.filter(LikeUsers=user)
    
    
    return render(request,'accounts/favorite_items.html', {'favorite_items':favorite_items})

src/top/views.py
from django.shortcuts import render
from django.views import generic
from django.db.models import Q

from items.models import Item


# Create your views here.
class TopView(generic.TemplateView):
    template_name = 'top.html'

# Topページを表示するためのビュー
def TopView(request):
    if request.method == "POST":
        SearchWord = request.POST.get("search")
        print(SearchWord)
        items_list = Item.objects.filter(
            Q(item_title__contains=SearchWord) |
            Q(item_explain__contains=SearchWord)
        )
    else:
        items_list = Item.objects.all()
    context = {
        "items_list":items_list,
    }
    return render(request, "top.html", context)

src/templates/accounts/base.html
{% load static %}

<!doctype html>
<html lang="ja">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- 互換表示の解除 -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <title>ユーザー登録・更新</title>
</head>

<body>
    <!-- ナビバー -->
    <nav class="navbar navbar-expand-md navbar-dark bg-light">
        <a class="navbar-brand" href="{% url 'top:top' %}">
            <img src="{% static 'img/top/logo.png' %}" class="col-5"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"></li>
                
            </ul>
        </div>
    </nav>
    <div class="pl-4 small" style="background-color: #e2e3e5 ; border-bottom: solid 1px #f3f3f3;">
        {% if not user.is_authenticated %}
        こんにちは！ ゲスト さん
        {% else %}
        こんにちは！ {{ user.username }} さん
        {% endif %}
    </div>
    <!-- コンテンツ -->
    {% block content %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

src/templates/accounts/delete.html
{% extends 'accounts/base.html' %}

{% block content %}
<div class="container">
    <div class="col-md-6 offset-md-3 text-center">
        <h1 class="text-danger">本当に退会しますか？</h1>
        <form role="form" method="post">
            {% csrf_token %}
            <p>あなたのアカウント「{{ user.username }}」を、本当に削除してもよろしいですか？</p>
        
            <button type="submit" class="btn btn-danger">削除</button>
            <a href="javascript:void(0);" onclick="window.history.back();" class="btn btn-secondary">キャンセル</a>
        </form>
    </div>
</div>
{% endblock %}

src/templates/accounts/delete_done.html
{% extends 'accounts/base.html' %}

{% block content %}
<div class="container">
    <div class="col-md-6 offset-md-3 text-center">
        <h3>退会処理が完了しました</h3>
        <a href="{% url 'top:top' %}" class="btn btn-dark" role="button">トップページに戻る</a>
    </div>
</div>
{% endblock %}

src/templates/accounts/login.html
{% extends 'accounts/base.html' %}

<!-- コンテンツ -->
{% block content %}
<div class="container">
    <div class="col-md-6 offset-md-3">
        <div class="card mt-3 mb-3 bg-light">
            <!-- カードヘッダー -->
            <div class="card-header bg-primary text-light">
                <h4>Log in</h4>
            </div>
            <!-- カードボディー -->
            <div class="card-body">
                <form action="" method="POST">
                    {{ form.non_field_errors }}
                    {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <br>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">ログイン</button>
                    <input type="hidden" name="next" value="{{ next }}" />
                    {% csrf_token %}
                </form>
                <a href="{% url 'account:reset_password' %}">パスワードを忘れた場合</a>
                <p>アカウントをお持ちでない場合</p>
                <a href="{% url 'account:signup' %}" class="btn btn-dark" role="button">サインイン</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/templates/accounts/logout.html
{% extends 'accounts/base.html' %}

<!-- コンテンツ -->
{% block content %}
<div class='container'>
    <div class="col-md-6 offset-md-3">
        <div class='card mt-3 mb-3 bg-light'>
            <!-- カードヘッダー -->
            <div class='card-header bg-primary text-light'>
                <h4>Log out</h4>
            </div>
            <!-- カードボディー -->
            <div class='card-body'>
                <p>ログアウトしました。</p>
                <p>ご利用ありがとうございました。</p>
                <hr class='mt-2 mb-2'>
                <p><a href="{% url 'account:login' %}">他のアカウントでログインする</a></p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/templates/accounts/my_page.html
{% extends 'accounts/base.html' %}
{% load static %}

<!-- コンテンツ -->
{% block content %}
<div class="container">
    <div class="float-right">
        <div class="card" style="width: 5rem;">
            <div class="position-relative">
                {% if user.profile_image %}
                <img src="{{ user.profile_image.url }}" class="card-img-top img-fluid rounded-circle"
                    style="height: 80%; object-fit: cover;">
                {% else %}
                <img src="{% static 'img/account/profile_default.png' %}" class="card-img-top rounded"
                    style="height: 80%; object-fit: cover;">
                {% endif %}
                <a href="{% url 'account:user_update' user.pk %}" id="profile_icon">
                    <i class="bi bi-pencil-square"></i>
                </a>
            </div>
        </div>
    </div>
    <h1>My page</h1>
    <hr>

    <!-- アカウント情報 -->
    <div class="row">
        <div class="col">
            <h4>■　登録情報</h4>
        </div>
    </div>
    <table class="table table-bordered">
        <tbody>
            <tr>
                <td style="width: 50%;">姓</td>
                <td style="width: 50%;">{{ user.last_name }}</td>
            </tr>
            <tr>
                <td>名</td>
                <td>{{ user.first_name }}</td>
            </tr>
            <tr>
                <td>メールアドレス</td>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <td>ユーザー名</td>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <td>住所</td>
                <td>{{ user.address }}</td>
            </tr>
            <tr>
                <td>電話番号</td>
                <td>{{ user.phone_number }}</td>
            </tr>
            <tr>
                <td>自己紹介文</td>
                <td>{{ user.bio }}</td>
            </tr>
        </tbody>
    </table>

    <!-- パスワード -->
    <div class="row mt-4">
        <div class="col">
            <h4>■　パスワード</h4>
        </div>
        <div class="col text-right"><a href="{% url 'account:password_change' %}">更新</a></div>
    </div>
    <table class="table table-bordered">
        <tbody>
            <tr>
                <td style="width: 50%;">パスワード</td>
                <td style="width: 50%;">非表示</td>
            </tr>
        </tbody>
    </table>
    <div class="text-center"><a href="{% url 'account:delete' user.pk %}" class="btn btn-danger" role="button">退会する</a>
    
    
    </div>
</div>
{% endblock %}

src/templates/accounts/password_change_done.html
{% extends "base.html" %}

<!-- コンテンツ -->
{% block content %}
<div class="container">
    <div class="col-md-6 offset-md-3">
        <div class="card mt-3 mb-3 bg-light">
            <!-- カードヘッダー -->
            <div class="card-header bg-success text-light">
                <h4>Change Password Done</h4>
            </div>
            <!-- カードボディー -->
            <div class="card-body">
                <p>パスワードを更新しました。</p>
                <hr>
                <a href="{% url 'account:my_page' user.pk %}">My page</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/templates/accounts/password_reset.html
{% extends 'accounts/base.html' %}

{% block content %}
<div class="container">
    <div class="col-md-6 offset-md-3">
        <div class="card mt-3 mb-3 bg-light">
            <div class="card-header bg-success text-light">
                <h4>Eメールアドレスを入力してください</h4>
            </div>
            <div class="card-body">
                <form method="post" style="padding-left:20px;">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Reset Password</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/templates/accounts/password_reset_complete.html
{% extends "base.html" %}

<!-- コンテンツ -->
{% block content %}
<div class="container">
    <div class="col-md-6 offset-md-3">
        <div class="card mt-3 mb-3 bg-light">
            <!-- カードヘッダー -->
            <div class="card-header bg-success text-light">
                <h4>パスワードリセット</h4>
            </div>
            <!-- カードボディー -->
            <div class="card-body">
                <p>パスワードリセットが完了しました。ログインページへお進みください。</p>
                <p class="text-danger">"ユーザー名"と"パスワード"は大切に管理してください。</p>
                <hr>
                <a href="{% url 'account:login' %}">Log in</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/templates/accounts/password_reset_confirm.html
{% extends 'accounts/base.html' %}

{% block content %}
<div class="container">
    <div class="col-md-6 offset-md-3">
        <div class="card mt-3 mb-3 bg-light">
            <!-- カードヘッダー -->
            <div class="card-header bg-success text-light">
                <h4>パスワードリセット</h4>
            </div>
            <!-- カードボディー -->
            <div class="card-body">
                <form action="" method="POST">
                    {{ form.non_field_errors }}
                    {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}
                    {% csrf_token %}
                    <!-- ボタン -->
                    <button type="submit" class="btn btn-success btn-lg btn-block mt-2">{{ process_name }}</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/templates/accounts/password_reset_sent.html
{% extends 'accounts/base.html' %}

{% block content %}
<div class="container">
    <div class="col-md-6 offset-md-3">
        <div class="card mt-3 mb-3 bg-light">
            <div class="card-header bg-success text-light">
                <h4>パスワードリセット．</h4>
            </div>
            <div class="card-body">
                メールが送られました．
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="col-md-6 offset-md-3">
        <div class="card mt-3 mb-3 bg-light">
            <!-- カードヘッダー -->
            <div class="card-header bg-success text-light">
                <h4>{{ process_name }}</h4>
            </div>
            <!-- カードボディー -->
            <div class="card-body">
                <form action="" method="POST">
                    {{ form.non_field_errors }}
                    {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}
                    {% csrf_token %}
                    <!-- ボタン -->
                    <button type="button" class="btn btn-outline-secondary btn-lg btn-block mt-4"
                        onclick="history.back()">キャンセル</button>
                    <button type="submit" class="btn btn-success btn-lg btn-block mt-2">{{ process_name }}</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/templates/accounts/signup_done.html
{% extends "base.html" %}

<!-- コンテンツ -->
{% block content %}
<div class="container">
    <div class="col-md-6 offset-md-3">
        <div class="card mt-3 mb-3 bg-light">
            <!-- カードヘッダー -->
            <div class="card-header bg-success text-light">
                <h4>Sign up Done</h4>
            </div>
            <!-- カードボディー -->
            <div class="card-body">
                <p>ユーザー登録が完了しました。ログインページへお進みください。</p>
                <p class="text-danger">"ユーザー名"と"パスワード"は大切に管理してください。</p>
                <hr>
                <a href="{% url 'account:login' %}">Log in</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/templates/accounts/top.html
{% extends "accounts/base.html" %}

<!-- コンテンツ -->
{% block content %}
<div class="container">
    <h1>Top Page!!</h1>
</div>
{% endblock %}