src/account/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from . import views

app_name = 'account'

urlpatterns = [
    path('', views.AccountView.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('my_page/<int:pk>/', views.MyPage.as_view(), name='my_page'),
    path('signup/', views.Signup.as_view(), name='signup'),
    path('signup_done/', views.SignupDone.as_view(), name='signup_done'),
    path('user_update/<int:pk>', views.UserUpdate.as_view(), name='user_update'),
    path('reset_password/', views.PasswordReset.as_view(), name='reset_password'),
    path('password_reset_sent', views.PasswordResetSent.as_view(), name='password_reset_sent'),
    path('password_reset_confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change_done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('delete/<int:pk>', views.UserDeleteView.as_view(), name='delete'),
    path('delete_done/', views.UserDeleteDoneView.as_view(), name='delete_done'),
    path('favorite_items/', views.FavoriteItems, name='favorite_items')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/ec_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('top/', include('top.urls')),
    path('account/', include('account.urls')),
    path('items/', include('items.urls')),
    path('settlement/', include('settlement.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/items/urls.py
from django.urls import include, path

from . import views

app_name = 'items'

urlpatterns = [
    path('add_item_page/', views.Add_Item_page, name='add_item'),
    path('add_item_completed/', views.Add_Item_Completed, name='add_item_completed'),
    path('item_details/<int:item_id>/', views.Item_Detail, name='item_details'),
    path('item_details/<int:item_id>/like/', views.LikeItem.as_view(), name='like'),
]

src/settlement/urls.py
from django.urls import include, path

from . import views

app_name = 'settlement'

urlpatterns = [
    path('AddressSelect/<int:item_id>', views.confirm, name='AddressSelect'),
    path('AddAddress/<int:user_id>', views.AddAddress.as_view(), name='AddAddress'),
    path('payment/', views.PayView.as_view(), name='payment')
]

src/top/urls.py
from django.urls import include, path

from . import views

app_name = 'top'

urlpatterns = [
    path('', views.TopView, name='top')
]

src/items/models.py
import os
import shutil

from django.core.files.storage import FileSystemStorage
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver

from account.models import CustomFileSystemStorage, User


# ファイルアップロード時にユーザーIDをフォルダ名として使用する
def user_directory_path(instance, filename):
    return f'item_images/item_{instance.id}/{filename}'

# 出品する商品テーブル
class Item(models.Model):
    item_title = models.CharField(max_length=100)
    item_explain = models.TextField()
    item_category = models.CharField(max_length=100)
    item_condition = models.CharField(max_length=100)
    item_price = models.IntegerField(validators=[MinValueValidator(50), MaxValueValidator(9999999)])
    seller = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    item_image = models.ImageField(upload_to=user_directory_path, blank=True, null=True, storage=CustomFileSystemStorage())
    likes = models.IntegerField(default=0, blank=True, null=True)
    LikeUsers = models.ManyToManyField(User, related_name='user', blank=True)
    is_bought = models.BooleanField(default=False, blank=True)


    def __str__(self):
        return self.item_title
    
    def save(self, *args, **kwargs):
        if self.pk is None:
            saved_image = self.item_image
            self.item_image = None
            super().save(*args, **kwargs)
            self.item_image = saved_image
            if "force_insert" in kwargs:
                kwargs.pop("force_insert")
        super().save(*args, **kwargs)
    
    
'''class Like(models.Model):
    item_id = '''

src/items/forms.py
from django import forms

from .models import Item

class Add_Item_Form(forms.Form):

    ITEM_CONDITION_CHOICES = [
        ('', '選択してください'),
        ('新品', '新品'),
        ('中古', '中古'),
    ]
    
    item_title = forms.CharField(label='商品名', max_length=100)
    item_explain = forms.CharField(label='商品説明',widget=forms.Textarea(attrs={'rows': 3}), max_length=1000)
    item_category = forms.CharField(label='カテゴリ', max_length=100)
    item_condition = forms.TypedChoiceField(
        choices=ITEM_CONDITION_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'}),
        coerce=str,  # 選択された値を文字列に変換
        empty_value='',  # 空の選択肢を設定
        label='商品の状態'
    )
    item_price = forms.IntegerField(label='価格',min_value=0)
    item_image = forms.ImageField(label='商品の写真')
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['item_title'].widget.attrs['placeholder'] = '商品名を入力してください'
        self.fields['item_category'].widget.attrs['placeholder'] = 'カテゴリを入力してください'
        self.fields['item_price'].widget.attrs['placeholder'] = '価格を入力してください'
        for field in self.fields.values():
            if field.label == '商品の写真':
                field.widget.attrs['class'] = 'custom-file-label'
                field.widget.attrs['id'] = 'inputFile'
                field.widget.attrs['type'] = 'file'
            if field.label != '商品の状態':
                field.widget.attrs['class'] = 'form-control'
    

src/items/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render

from .forms import Add_Item_Form
from .models import Item

from rest_framework.views import APIView
from rest_framework.response import Response


# 商品を出品するフォームページを表示するビュー
@login_required
def Add_Item_page(request):
    # フォームが送信された場合
    if request.method == "POST":
        form = Add_Item_Form(request.POST, request.FILES)
        if form.is_valid():
            item_title = form.cleaned_data['item_title']
            item_explain = form.cleaned_data['item_explain']
            item_category = form.cleaned_data['item_category']
            item_condition = form.cleaned_data['item_condition']
            item_price = form.cleaned_data['item_price']
            item_image = form.cleaned_data['item_image']
            seller = request.user
            Item.objects.create(
                item_title=item_title,
                item_explain=item_explain,
                item_category=item_category,
                item_condition=item_condition,
                item_price=item_price,
                seller=seller,
                item_image=item_image,
            )
            return redirect('items:add_item_completed')
    else:
        form = Add_Item_Form()
    
    return render(request, 'items/add_item.html', {'form': form})


# 商品追加完了ページへのビュー
def Add_Item_Completed(request):
    
    return render (request, 'items/add_item_completed.html')


def Item_Detail(request, item_id):
    item = get_object_or_404(Item, pk=item_id)
    if request.method == 'POST' and request.POST.get('action') == 'like':
        current_likes = request.session.get('likes', 0)
        new_likes = current_likes + 1
        request.session['likes'] = new_likes

        # 応答を作成して返す
        return JsonResponse({'success': True, 'likes': new_likes})
    else:
        return render(request, 'items/item_detail.html', {'item':item})
    
# 商品のいいねをするためのビュー
class LikeItem(APIView):
    def post(self, request, item_id):
        item = get_object_or_404(Item, pk=item_id)
        
        # ユーザーがまだいいねしていない場合のみitem.likesを増やす
        if not item.LikeUsers.filter(pk=request.user.pk).exists():
            item.LikeUsers.add(request.user)
            item.likes += 1
            request.session['likes'] = item.likes
            item.save()
        
        else:
            user = get_object_or_404(item.LikeUsers, pk=request.user.pk)
            item.LikeUsers.remove(user)
            item.likes -= 1
            request.session['likes'] = item.likes
            item.save()

        return Response({'success': True, 'likes': item.likes})
        

src/templates/items/add_item.html
{% extends './base.html' %}

{% block content %}
<div class="container">
    <br>
    <h1>出品ページ</h1>
    <hr>

    <form method="post" action="{%url 'items:add_item'%}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="item_title_input" class="form-label">{{form.item_title.label_tag}}</label>
            {{form.item_title}}
        </div>
        <div class="mb-3">
            <label for="item_explain_input" class="form-label">{{form.item_explain.label_tag}}</label>
            {{form.item_explain}}
        </div>
        <div class="form-group">
            <label for="inputFile">{{form.item_image.label_tag}}</label>
            <div class="custom-file">
                {{form.item_image}}
                {% comment %} 次のコード書くとデザインきれいになるけれど、選択したファイル名が表示されなくなる
                <label class="custom-file-label" for="inputFile">Choose file</label> {% endcomment %}
            </div>
        </div>
        <div class="mb-3">
            <label for="item_category_input" class="form-label">{{form.item_category.label_tag}}</label>
            {{form.item_category}}
        </div>
        <div class="mb-3">
            <label for="item_condition_input" class="form-label">{{form.item_condition.label_tag}}</label>
            {{form.item_condition}}
        </div>
        <div class="mb-3">
            <label for="item_price_input" class="form-label">{{form.item_price.label_tag}}</label>
            {{form.item_price}}
        </div>
        <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary btn-lg">出品する</button>
        </div>
    </form>
   
    
</div>


{% endblock %}

src/templates/items/add_item_completed.html
{% extends './base.html' %}

{% block content %}
<p>出品が完了しました!!</p>

{% endblock %}

src/templates/items/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ECサイト</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <script src="{% static 'js/like.js' %}"></script>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'top:top' %}"><img src="{% static 'img/top/logo.png' %}"
                    class="col-5"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="検索" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">検索</button>
                </form>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">

                        {% if not user.is_authenticated %}
                        <a href="{% url 'account:login' %}" class="btn btn-dark" role="button">ログイン</a>
                        {% else %}
                        <div class="dropdown">
                            <button id="btnOpenMenu" class="btn btn-dark dropdown-toggle" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                                ユーザメニュー
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="btnOpenMenu">
                                <li><a class="dropdown-item" href="{% url 'account:my_page' user.pk %}">マイページ</a></li>
                                <li><a class="dropdown-item" href="{% url 'account:logout' %}">ログアウト</a></li>
                            </ul>
                        </div>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <!-- ここにコンテンツを追加 -->
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>

</html>

src/templates/items/item_detail.html
{% extends '../base.html' %} {% load static %} {%block js%}
<script src="{% static 'js/like.js' %}"></script>
{% endblock%} {% block content %}
<div class="container-xl mb-5">
    <div class="col-12">
        <div class="row my-4">
            <div class="col-12 col-sm-6">
                <div class="row">
                    <div class="item_visual col-12 col-sm-10 order-sm-2 px-0 px-sm-3">
                    {% if item.item_image%}
                    <div class="slide-item">
                        <img src="{{ item.item_image.url }}" alt="" class="img-fluid" />
                    </div>
                    {% else %}
                    <div class="slide-item">
                        <img
                        src="\media\item_images\item_None\20220110-00051273-bunshun-000-2-view.jpg"
                        alt=""
                        class="img-fluid"/>
                    </div>
                    {% endif %}
                    </div>
                    <div class="col-12 col-sm-2 order-sm-1 pe-sm-0">
                    <div class="row">
                        <div class="col-2 col-sm-12 pe-0 px-sm-2">
                        {% if item.item_image%}
                        <img
                            src="{{ item.item_image.url }}"
                            alt=""
                            class="img-fluid pb-2"
                        />
                        {% else %}
                        <img
                            src="\media\item_images\item_None\20220110-00051273-bunshun-000-2-view.jpg"
                            alt=""
                            class="img-fluid pb-2"
                        />
                        {% endif %}
                        </div>
                    </div>
                    </div>
                </div>
            </div>

            <div class="col-12 col-sm-6">
                <h1 class="fs-4 fw-bold pt-3">{{item.item_title}}</h1>

                <h5 class="fs-4 pb-2 fw-bold text-danger">
                    <span class="price02-default">￥{{item.item_price}}</span>
                </h5>

                <div>
                    {% if request.user in item.LikeUsers.all %}
                    <button
                    id="likeButton"
                    type="button"
                    style="background: none; border: none"
                    >
                    <i class="bi bi-heart-fill" style="color: red"></i>
                    </button>
                    {% else %}
                    <button
                    id="likeButton"
                    type="button"
                    style="background: none; border: none"
                    >
                    <i class="bi bi-heart-fill" style="color: #ccc"></i>
                    </button>
                    {% endif %}
                    <span id="likeCount">{{item.likes}}</span> Likes
                </div>

                <a
                    href="{% url 'settlement:AddressSelect' item.pk %}"
                    class="btn btn-danger"
                    role="button"
                    >購入手続きへ</a
                >

                <div class="my-4">
                    <h4>商品の説明</h4>
                    <h5>{{item.item_explain}}</h5>
                </div>

                <div>
                    <h4>商品の情報</h4>
                    -----------------------------------------------------
                    <div class="d-flex justify-content-around">
                    <h5>カテゴリー</h5>
                    {{item.item_category}}
                    </div>
                    <div class="d-flex justify-content-around">
                    <h5>商品の状態</h5>
                    {{item.item_condition}}
                    </div>
                    <div class="d-flex justify-content-around">
                    <h5>配送料の負担</h5>
                    　
                    </div>
                    <div class="d-flex justify-content-around">
                    <h5>配送料の方法</h5>
                    　
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
  {% endblock %}
</div>